@include('header')
            <div class="blogs-banner  cspt-bg-color-transparent cspt-bg-image-yes">
                <div class="container">
                    <div class="cspt-title-bar-content">
                        <div class="cspt-title-bar-content-inner">
                            <div class="cspt-tbar">
                                <div class="cspt-tbar-inner container">
                                    <!-- <h1 class="cspt-tbar-title"> Kenclozer</h1> -->
                                </div>
                            </div>
                            <div class="cspt-breadcrumb">
                                <!-- <div class="cspt-breadcrumb-inner"><span><a title=""
                                            href=""
                                            class="home"><span>Our Brands</span></a></span><i
                                        class="cspt-base-icon-angle-right"></i><span
                                        class="post post-page current-item">Kenclozer</span></div> -->
                            </div>
                        </div>
                    </div><!-- .cspt-title-bar-content -->
                </div><!-- .container -->
            </div><!-- .cspt-title-bar-wrapper -->
        </header><!-- #masthead -->
        <div class="site-content-contain">
            <div id="content" class="site-content container blogContent">
                <div class="row multi-columns-row mt-5">

                    <div id="primary" class="content-area col-md-12 col-lg-12">
                        <main id="main" class="site-main">

                            <article id="post-278" class="post-278 post type-post status-publish format-standard has-post-thumbnail hentry category-electricity tag-energy">
                                <div class="cspt-featured-wrapper text-center"><img width="600" height="600"
                                            src="public/images/blog4.jpg"
                                            class="attachment-full size-full wp-post-image" alt="all-you-should-know-about-solar-energy"
                                            srcset="public/images/blog4.jpg 1200w, public/images/blog4.jpg 300w, public/images/blog4.jpg 768w, public/images/blog4.jpg 1024w, public/images/blog4.jpg 770w"
                                            sizes="(max-width: 1200px) 100vw, 1200px" data-id="8999" /></div>
                                <h1 class="cspt-post-title mt-5">All You Should Know About Solar Energy</h1>
                                <div class="cspt-blog-meta cspt-blog-meta-top">
                                    <span class="cspt-meta cspt-meta-date">
                                        <a href="#" rel="bookmark"><span
                                                class="entry-date published">March 31, 2022</span></a>
                                    </span>
                                </div>
                                <div class="cspt-blog-classic">
                                    <h2>What is Solar Energy?</h2>
                                    <p>Solar Energy is any kind of energy generated by the sun. Solar energy can be harnessed directly or indirectly for human use.</p>
                                    <p>Solar Power works by converting sunlight to electricity. This electricity can then be used and also can be exported to the grid when it’s not needed. This is achieved by installing rooftop solar which generate DC (Direct Current) electricity. This energy is then fed into a solar inverter which converts the DC electricity from your solar panels into AC (Alternating Current) electricity.</p>

                                    <div class="cspt-blog-classic-inner">
                                        <div class="cspt-blog-meta-wrapper ">
                                        </div>

                                        <div class="cspt-entry-content">
                                            <h2>How does it Work?</h2>
                                            <p>The solar cells which are present in solar panels also referred to as photovoltaic cells, absorb sunlight during daylight hours. Within each solar cell there is a thin semiconductor wafer made from two layers of silicon. One layer is positively charged and other is negatively charged, forming an electric field. When sunlight strikes a solar cell, it energizes the cell and causes electrons to ‘come loose’ from atoms within the semiconductor wafer. Those loose electrons are set into motion by the electric field and this motion creates an electrical current.</p>
                                            <p>As solar rooftop panel is working efficiently to transform sunlight into electricity but generated electricity generated is DC (Direct Current) which is not the type of electricity that powers most homes. This DC electricity can easily be changed into AC (Alternating Current) electricity by an equipment called a solar inverter. This AC electricity from <a href="https://www.ksquareenergy.com/products/Sofar%20Inverter">solar inverter</a> is directed to your switch board in homes. Home’s switchboard will ensure that solar energy will be used first and only accessing additional energy from the grid when your solar production is not enough.</p>
                                            <p>During the formation of surplus energy in a day, Net Meter are used for collection so when it is night time or cloudy and panels are not able to capture enough sunlight to produce energy, your home is operated by collected surplus energy that is stored is net meter. For this reason meter is used to measure the electricity flowing in both directions—to and from your home.</p>
                                            <p>An unused solar electricity is sent back to the grid. Exporting solar power back to the grid earns you a credit on your electricity bill. Your electricity service provider will then take into account the electricity you purchase from the grid, plus credits for the electricity generated by your solar power system that you don’t use. <a href="https://100percentrenewables.com.au/nine-ways-maximise-financial-benefit-surplus-solar-energy/">More ways to maximise the financial benefits from surplus solar energy.</a></p>
                                            <hr>
                                            <h2>Impact of Solar on Environment</h2>
                                            <ul>
                                                <li>Solar will reduce greenhouse gas and CO2 emissions</li>
                                                <li>Solar reduces water pollution</li>
                                                <li>Solar reduces strain on finite resources</li>
                                            </ul>
                                            <hr>
                                            <h2>Advantages of Solar Energy</h2>
                                            <ul>
                                                <li>It is renewable energy resource</li>
                                                <li>It reduces electricity bills</li>
                                                <li>Low maintenance cost</li>
                                                <li>Technology development</li>
                                            </ul>
                                            <hr>
                                            <h2>Disadvantages of Solar</h2>
                                            <ul>
                                                <li>Initial cost of solar is high</li>
                                                <li>It is weather dependent</li>
                                                <li>It use more space in your premises</li>
                                            </ul>
                                            <hr>
                                            <h2>Save Money & Save Environment</h2>
                                            <p>Now that we know the basics about solar, you can wonder how today’s photovoltaic technology can capture the vast power of the sun to operate. So, go solar for savings on electricity bills and also betterment of environment.</p>
                                            <hr>
                                            <h2>Who We Are?</h2>
                                            <p><a href="https://www.ksquareenergy.com">Ksquare Energy</a> is leading manufacturer & supplier of solar compants & contractor of Soalr EPC projects. We have experienced team of Solar Energy professionals who can consult you best solar solutions.</p>
                                            <p>So, Visit our <a href="https://www.ksquareenergy.com/contact-us">Contact Us</a> section for more information and fill-up the form to get in touch with us.</p>
                                            <p>You can also email us your queries to info@ksquareenergy.com or call us on +91 7227931916/17 for any kind of details.</p>
                                            
                                        </div><!-- .entry-content -->
                                        
                                    </div>
                                </div>
                            </article><!-- #post-## -->
                            
                        </main><!-- #main -->
                    </div><!-- #primary -->

                   
                </div><!-- .row -->

            </div><!-- #content -->
@include('footer')